name: Build and Install Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper-compat dh-autoreconf fakeroot

      - name: Build Debian package
        run: |
          cd src
          make
          mkdir -p ../debian/usr/bin
          mv main ../debian/usr/bin/gitActionFlow
          cd ..
          dpkg-buildpackage -b

      - name: Move .deb file to workspace root
        run: |
          mv ../*.deb .   # Move the .deb file to the workspace root

      - name: Archive .deb package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: '*.deb'
          if-no-files-found: warn
          include-hidden-files: false

  test-package:
    needs: build-package
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Debian package
        uses: actions/download-artifact@v3
        with:
          name: debian-package

      - name: Install the package in Docker container
        run: |
          apt-get update
          dpkg -i *.deb || apt-get install -f
          #dpkg -i ../*.deb || sudo apt-get install -f

      - name: Run installed program
        run: |
          main

