name: Build Debian Package

on:
  push:
    paths:
      - 'Version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Get version from file
      id: get_version
      run: echo "VERSION=$(cat Version.txt)" >> $GITHUB_ENV

    - name: Compile source code
      run: |
        # Replace these commands with your actual build commands
        #mkdir -p build
        #cd source  # Replace with your source directory
        # Example compilation commands:
        # make clean
        # make all
        # You can add your specific compilation steps here
        cd src
        make

    - name: Create debian package structure
      run: |
        mkdir -p debian/DEBIAN
        mkdir -p debian/usr/local/bin

        # Copy compiled binaries to debian package structure
        cp src/* debian/usr/local/bin/

        # Create control file
        cat > debian/DEBIAN/control << EOF
        Package: testHelloworld
        Version: ${{ env.VERSION }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Shariful Alam <alam.shariful@hotmail.com>
        Description: Test Package
         A longer description of your package
         that can span multiple lines.
        EOF

    - name: Build debian package
      run: |
        dpkg-deb --build debian
        mv debian.deb testHelloworld_${{ env.VERSION }}_amd64.deb

    - name: Move package to storage directory
      run: |
        mkdir -p packages
        mv *.deb packages/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: packages/*.deb

